#print("Ingresa el valor de a")
a=2 #a = float(input())
#print("Ingresa el valor de b")
b=4 #b = float(input())
#print("Ingresa el valor de c")
c=-6 #c = float(input())
x1 = (-b + (b**2-(4*a*c))**0.5)/(2*a)
x2 = (-b - (b**2-(4*a*c))**0.5)/(2*a)
print("x1 =",x1)
print("x2 =",x2)